# Generated by Django 3.1.5 on 2021-01-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.studiedvocable')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.sentence')),
            ],
        ),
    ]
