# Generated by Django 3.1.5 on 2021-01-17 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudiedVocable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_studied', models.DateTimeField(blank=True)),
                ('correct_studied', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocable')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabs', models.ManyToManyField(to='vocabulary.Vocable')),
            ],
        ),
    ]
