# Generated by Django 3.1.5 on 2021-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='vocabs',
            field=models.ManyToManyField(blank=True, related_name='sets', to='vocabulary.Vocable'),
        ),
    ]
