# Generated by Django 3.1.5 on 2021-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_auto_20210118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
